### ISSUE TITLE
Mangoware on Docker

### ISSUE THREAD

**Issue by kalhori124** [MAGOWARE/backoffice-administration#84]
Hi,

I installed Docker on a fresh CentOS 7 but I can't find Mangoware build to pull.
Is there any install documents to have Mangoware on Docker ?

Best Regards,

**Comment by jessequinn** [comment]
I would assume you need to build your own docker-compose etc. I am doing this now. If i can get it to work I will share.

**Comment by jessequinn** [comment]
you could use something like this

```
version: "3.7"

services:
  #######################
  # Magoware
  #######################
  app:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    restart: unless-stopped
    environment:
      DB_NAME: magoware
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: xio9alaitavooR5f
      DB_DIALECT: mysql
      DB_SSL: "false"
      DB_SYNC: "true"
    command: "./node_modules/.bin/sequelize db:migrate"
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
  #######################
  # Redis 5
  #######################
  redis:
    image: redis:5.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
  #######################
  # Mysql 5.7
  #######################
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: xio9alaitavooR5f
      MYSQL_DATABASE: magoware
    ports:
      - "3306:3306"
  #######################
  # Adminer for mysql administration
  #######################
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
```
However i have issues testing as i am missing the base tables required to build this system. You need to purchase this? I am trying to make a development server so i can push some PRs for my company that did purchase this software! There is a fundamental issue with the API create subscription.
